name: Tag Release on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  tag_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "miguelapabenedit"
        git config user.email "miguell.beneditt@gmail.com"

    - name: Get current version
      id: get_version
      run: |
        # Default to 0.0.0 if no tags exist
        CURRENT_VERSION=$(git tag --sort=-v:refname | head -n 1 || echo "0.0.0")
        echo "current_version=$CURRENT_VERSION" >> $GITHUB_ENV

    - name: Increment version
      id: increment_version
      run: |
        # Parse current version
        IFS='.' read -r -a PARTS <<< "$CURRENT_VERSION"
        MAJOR=${PARTS[0]}
        MINOR=${PARTS[1]}
        PATCH=${PARTS[2]}

        # Increment the appropriate part
        case "${{ github.event.pull_request.title }}" in
          *#major*) ((MAJOR+=1)) MINOR=0 PATCH=0 ;;
          *#minor*) ((MINOR+=1)) PATCH=0 ;;
          *)        ((PATCH+=1)) ;;
        esac

        NEW_VERSION="$MAJOR.$MINOR.$PATCH"
        echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

    - name: Tag the release
      run: |
        git tag ${{ env.new_version }}
        git push origin ${{ env.new_version }}